import math

FRAME_WIDTH = 800
FRAME_HEIGHT = 600
TILE_WIDTH_SIZE = 42
TILE_HEIGHT_SIZE = 18
TILE_WIDTH = math.floor(FRAME_WIDTH / TILE_WIDTH_SIZE)
TILE_HEIGHT = math.floor(FRAME_HEIGHT / TILE_HEIGHT_SIZE)
MAX_X_TILES = 100
MAX_Y_TILES = 100
